<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2016 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
$this->headTitle(__('Page Not Found'));
?>
<p></p>
<main id="page-main-region" class=" page-main-wrapper container-fluid"
      role="main">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2><?php echo __('A 404 error occurred') ?></h2>

            <p><?php echo $this->message ?></p>
        </div>
        <div class="panel-body">
            <?php if (isset($this->reason) && $this->reason): ?>

                <?php
                $reasonMessage = '';
                switch ($this->reason) {
                    case 'error-controller-cannot-dispatch':
                        $reasonMessage = __(
                            'The requested controller was unable to dispatch the request.'
                        );
                        break;
                    case 'error-controller-not-found':
                        $reasonMessage = __(
                            'The requested controller could not be mapped to an existing controller class.'
                        );
                        break;
                    case 'error-controller-invalid':
                        $reasonMessage = __(
                            'The requested controller was not dispatchable.'
                        );
                        break;
                    case 'error-router-no-match':
                        $reasonMessage = __(
                            'The requested URL could not be matched by routing.'
                        );
                        break;
                    default:
                        $reasonMessage = __(
                            'We cannot determine at this time why a 404 was generated.'
                        );
                        break;
                }
                ?>

                <p><?php echo $reasonMessage ?></p>

            <?php endif ?>

            <?php if (isset($this->controller) && $this->controller): ?>

                <dl>
                    <dt><?php echo __('Controller') ?>:</dt>
                    <dd><?php echo e($this->controller) ?>
                        <?php
                        if (isset($this->controller_class)
                            && $this->controller_class
                            && $this->controller_class != $this->controller
                        ) {
                            echo
                                '(' . sprintf(
                                    __('resolves to %s'),
                                    e($this->controller_class)
                                ) . ')';
                        }
                        ?>
                    </dd>
                </dl>

            <?php endif ?>

            <?php if (isset($this->display_exceptions)
                && $this->display_exceptions
            ): ?>

                <?php
                if (isset($this->exception)
                    && $this->exception instanceof Throwable
                ):
                    ?>
                    <hr/>
                    <h2><?php echo __('Additional information') ?>:</h2>
                    <h3><?php echo get_class($this->exception); ?></h3>
                    <dl>
                        <dt><?php echo __('File') ?>:</dt>
                        <dd>
                <pre
                    class="prettyprint linenums"><?php
                    echo $this->exception->getFile()
                    ?>
                    :<?php echo $this->exception->getLine() ?></pre>
                        </dd>
                        <dt><?php echo __('Message') ?>:</dt>
                        <dd>
                <pre
                    class="prettyprint linenums"><?php
                    echo $this->exception->getMessage()
                    ?></pre>
                        </dd>
                        <dt><?php echo __('Stack trace') ?>:</dt>
                        <dd>
                <pre
                    class="prettyprint linenums"><?php
                    echo $this->exception->getTraceAsString()
                    ?></pre>
                        </dd>
                    </dl>
                    <?php
                    $e = $this->exception->getPrevious();
                    if ($e) :
                        ?>
                        <hr/>
                        <h2><?php echo __('Previous exceptions') ?>:</h2>
                        <ul class="unstyled">
                            <?php while ($e) : ?>
                                <li>
                                    <h3><?php echo get_class($e); ?></h3>
                                    <dl>
                                        <dt><?php echo __('File') ?>:</dt>
                                        <dd>
                                <pre
                                    class="prettyprint linenums"><?php
                                    echo $e->getFile()
                                    ?>
                                    :<?php echo $e->getLine() ?></pre>
                                        </dd>
                                        <dt><?php echo __('Message') ?>:</dt>
                                        <dd>
                                <pre
                                    class="prettyprint linenums"><?php
                                    echo $e->getMessage()
                                    ?></pre>
                                        </dd>
                                        <dt><?php echo __('Stack trace') ?>:
                                        </dt>
                                        <dd>
                                <pre
                                    class="prettyprint linenums"><?php
                                    echo $e->getTraceAsString()
                                    ?></pre>
                                        </dd>
                                    </dl>
                                </li>
                                <?php
                                $e = $e->getPrevious();
                            endwhile;
                            ?>
                        </ul>
                    <?php endif; ?>

                <?php else: ?>

                    <h3><?php echo __('No Exception available') ?></h3>

                <?php endif ?>

                <?php

            endif ?>
        </div>
    </div>
</main>