<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2016 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
$this->headTitle(__('Sorry, something went wrong.'));
?>
<h1><?php echo __('An error occurred') ?></h1>
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

    <?php
    if (isset($this->exception) && $this->exception instanceof Throwable
    ):
        ?>
        <hr/>
        <h2><?php echo __('Additional information') ?>:</h2>
        <h3><?php echo get_class($this->exception); ?></h3>
        <dl>
            <dt><?php echo __('File') ?>:</dt>
            <dd>
                <pre
                        class="prettyprint linenums"><?php
                    echo $this->exception->getFile()
                    ?>
                    :<?php echo $this->exception->getLine() ?></pre>
            </dd>
            <dt><?php echo __('Message') ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php
                    echo e(
                        $this->exception->getMessage()
                    )
                    ?></pre>
            </dd>
            <dt><?php echo __('Stack trace') ?>:</dt>
            <dd>
                <pre
                        class="prettyprint linenums"><?php
                    echo e(
                        $this->exception->getTraceAsString()
                    )
                    ?></pre>
            </dd>
        </dl>
        <?php
        $e = $this->exception->getPrevious();
        if ($e) :
            ?>
            <hr/>
            <h2><?php echo __('Previous exceptions') ?>:</h2>
            <ul class="unstyled">
                <?php while ($e) : ?>
                    <li>
                        <h3><?php echo get_class($e); ?></h3>
                        <dl>
                            <dt><?php echo __('File') ?>:</dt>
                            <dd>
                                <pre
                                        class="prettyprint linenums"><?php
                                    echo $e->getFile()
                                    ?>
                                    :<?php echo $e->getLine() ?></pre>
                            </dd>
                            <dt><?php echo __('Message') ?>:</dt>
                            <dd>
                                <pre
                                        class="prettyprint linenums"><?php
                                    echo e(
                                        $e->getMessage()
                                    )
                                    ?></pre>
                            </dd>
                            <dt><?php echo __('Stack trace') ?>:
                            </dt>
                            <dd>
                                <pre
                                        class="prettyprint linenums"><?php
                                    echo e(
                                        $e->getTraceAsString()
                                    )
                                    ?></pre>
                            </dd>
                        </dl>
                    </li>
                    <?php
                    $e = $e->getPrevious();
                endwhile;
                ?>
            </ul>
        <?php endif; ?>

    <?php else: ?>

        <h3><?php echo __('No Exception available') ?></h3>

    <?php endif ?>

    <?php

endif ?>
