wellcart:
  build: .
  dockerfile: Dockerfile
  ports:
   - "8080:80"
  links:
    - mariaDB
  command: /usr/sbin/apache2ctl -D FOREGROUND
  volumes:
   - .:/var/www/html
mariaDB:
  image: mariadb
  environment:
    MYSQL_DATABASE: root
    MYSQL_ROOT_PASSWORD: root