<?php
namespace WellCart\Catalog\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-22 at 05:51:25.
 */
class PersistProductTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PersistProduct
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PersistProduct;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers WellCart\Catalog\Command\PersistProduct::getForm
     * @todo   Implement testGetForm().
     */
    public function testGetForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellCart\Catalog\Command\PersistProduct::setForm
     * @todo   Implement testSetForm().
     */
    public function testSetForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
