<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2017 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
?>
<p class="greeting"><?php echo $user->getDisplayName() ?>,</p>
<p><?php
    echo sprintf(
        __(
            "You must confirm your %s email before you can sign in (link is only valid once):"
        ), $user->getEmail()
    )
    ?></p>

<table class="button" width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td>
            <table class="inner-wrapper" border="0" cellspacing="0"
                   cellpadding="0" align="center">
                <tr>
                    <td align="center">
                        <a href="<?php echo e($url) ?>" target="_blank">
                            <?php echo __("Confirm Your Account") ?>
                        </a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

