<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2017 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
?>
<h3><?php echo $user->getDisplayName() ?>,</h3>

<p><?php
    echo __(
        "There was recently a request to change the password for your account."
    )
    ?></p>

<p><?php
    echo __(
        "If you requested this change, reset your password here:"
    )
    ?></p>

<p><a href="<?php echo e($url) ?>"><?php echo e($url) ?></a></p>

<p><?php
    echo __(
        "If you did not make this request, you can ignore this email and your password will remain the same."
    )
    ?></p>

<p><?php echo __("Thank you.") ?></p>