<?php
namespace WellCart\Catalog\Command\Handler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-22 at 05:50:45.
 */
class PersistProductHandlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PersistProductHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PersistProductHandler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers WellCart\Catalog\Command\Handler\PersistProductHandler::handle
     * @todo   Implement testHandle().
     */
    public function testHandle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
