<?php
namespace WellCart\Catalog\Controller\Backend;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-22 at 05:53:14.
 */
class FeaturesControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FeaturesController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FeaturesController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers WellCart\Catalog\Controller\Backend\FeaturesController::listAction
     * @todo   Implement testListAction().
     */
    public function testListAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellCart\Catalog\Controller\Backend\FeaturesController::createAction
     * @todo   Implement testCreateAction().
     */
    public function testCreateAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellCart\Catalog\Controller\Backend\FeaturesController::handleForm
     * @todo   Implement testHandleForm().
     */
    public function testHandleForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellCart\Catalog\Controller\Backend\FeaturesController::updateAction
     * @todo   Implement testUpdateAction().
     */
    public function testUpdateAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellCart\Catalog\Controller\Backend\FeaturesController::deleteAction
     * @todo   Implement testDeleteAction().
     */
    public function testDeleteAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellCart\Catalog\Controller\Backend\FeaturesController::attemptToPersistEntity
     * @todo   Implement testAttemptToPersistEntity().
     */
    public function testAttemptToPersistEntity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellCart\Catalog\Controller\Backend\FeaturesController::attemptToDeleteEntity
     * @todo   Implement testAttemptToDeleteEntity().
     */
    public function testAttemptToDeleteEntity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellCart\Catalog\Controller\Backend\FeaturesController::attemptToPerformGroupAction
     * @todo   Implement testAttemptToPerformGroupAction().
     */
    public function testAttemptToPerformGroupAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
