<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2017 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
use ZfcDatagrid\Column\Type;

$hasGroupActions = false;
if (count($this->massActions) > 0) {
    $hasGroupActions = true;
}


$searchFilters = $this->gridFilters($this->scope);
$filtersForm = $searchFilters->getForm();
$sorterLinks = $searchFilters->getSorterLinks();
?>
<?php echo $this->toolbar; ?>
<?php echo $this->partial(
    $this->templateToolbar, $this->vars()
); ?>
<div class="grid-main-container">
    <?php echo $this->form()->openTag($filtersForm); ?>

    <table class="table table-striped table-bordered table-datagrid"
           id="table-<?php echo $this->gridId ?>">
        <thead>
        <tr>
            <?php
            if ($hasGroupActions === true) :?>
                <th>
                    <div class="btn-group">
                        <button type="button"
                                class="btn btn-default btn-xs dropdown-toggle"
                                data-toggle="dropdown"
                                aria-haspopup="true"
                                aria-expanded="false"
                                id="btn-select-all-<?php echo $this->gridId ?>">
                            <input
                                    type="checkbox"
                                    id="checkbox-select-all-<?php echo $this->gridId; ?>"/>
                            <input type="hidden" name="selection_type"
                                   id="selection-type-<?php echo $this->gridId; ?>"
                                   value="none">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="#"
                                   onclick="<?php echo $this->gridId; ?>ChangeSelection('all'); return false;"><?php echo __(
                                        'All'
                                    ) ?></a></li>
                            <li><a href="#"
                                   onclick="<?php echo $this->gridId; ?>ChangeSelection('selected'); return false;"><?php echo __(
                                        'All Visible'
                                    ) ?></a></li>
                            <li><a href="#"
                                   onclick="<?php echo $this->gridId; ?>ChangeSelection('none'); return false;"><?php echo __(
                                        'None'
                                    ) ?></a></li>
                        </ul>
                    </div>
                </th>
            <?php endif;
            foreach ($this->columns as $col) {
                /* @var $col \ZfcDatagrid\Column\AbstractColumn */
                $columnId = $col->getUniqueId();
                $classes = array();
                $styles = array();

                $id = $col->getUniqueId();

                $label = '';
                if ($col->getLabel() != '') {
                    $label = $this->translate($col->getLabel());
                }

                $width = $col->getWidth();
                if ($width != '') {
                    $styles[] = 'width: ' . $this->escapehtmlattr($width)
                        . '%';
                }


                if ($col->isHidden() === true) {
                    $classes[] = 'hidden';
                }
                if ($col->getType() instanceof Type\Number) {
                    $styles[] = 'text-align: right';
                }
                ?>
                <th id="<?php echo $this->escapehtmlattr($id); ?>"
                    class="<?php echo implode(',', $classes); ?>"
                    style="<?php echo implode(';', $styles); ?>">
                    <?php if ($col->isSortable()): ?>
                        <?php echo $sorterLinks->link($columnId, $label); ?>
                    <?php else: ?>
                        <?php echo $label; ?>
                    <?php endif ?>
                </th>
                <?php
            }
            ?>
        </tr>


        <!-- User filters -->
        <?php if ($this->isUserFilterEnabled === true): ?>
            <tr class="filters-row">
                <?php
                if ($hasGroupActions === true) {
                    echo '<td></td>';
                }
                foreach ($this->columns as $col) {
                    /* @var $col \ZfcDatagrid\Column\AbstractColumn */
                    $columnId = $col->getUniqueId();
                    $classes = array();
                    if ($col->isHidden() === true) {
                        $classes[] = 'hidden';
                    }

                    $htmlFilter = '';
                    if ($col instanceof \ZfcDatagrid\Column\Action) {
                        $htmlFilter = '<div class="btn-group">' .
                            $this->formButton(
                                $filtersForm->get('apply_filters'),
                                __('Search')
                            ) . ' ' .
                            $this->formButton(
                                $filtersForm->get('reset_filters'),
                                __('Reset')
                            ) . '</div>';
                    } elseif ($col->isFilterable()
                        && $filtersForm->has(
                            $columnId
                        ) === true
                    ) {
                        $htmlFilter = $this->formElement(
                            $filtersForm->get($columnId)
                        );
                    }
                    ?>
                    <td class="<?php echo implode(',', $classes); ?>">
                        <?php echo $htmlFilter; ?>
                    </td>
                    <?php
                }
                ?>
            </tr>
        <?php endif; ?>


        </thead>
        <!-- END table header -->

        <!-- Start table BODY -->
        <tbody>
        <?php if (count($this->data)): ?>
            <?php foreach ($this->data as $row): ?>
                <?php
                echo $this->bootstrapTableRow(
                    $row, $this->columns, $this->rowClickAction,
                    $this->rowStyles, $hasGroupActions
                );
                ?>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="<?php echo count($this->columns) ?>"
                    class="text-center"><?php
                    echo $this->__(
                        'No records found'
                    )
                    ?></td>
            </tr>
        <?php endif ?>
        </tbody>
    </table>
    <?php echo $this->form()->closeTag(); ?>
    <?php
    echo $this->paginationControl(
        $this->paginator, null, null, ['route' => $route]
    );
    ?>

    <?php
    echo $this->partial(
        'wellcart-backend/page-view/grid/standard/footer-toolbar',
        $this->vars()
    );
    ?>
</div>
