<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2016 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
?>
<?php echo $this->doctype() . PHP_EOL; ?>
<html lang="<?php echo $this->locale()->getLanguage()->getCode() ?>">
<head>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->HtmlHead ?>
</head>
<body id="html-body-region" class="<?php echo $this->bodyClass() ?>">
<?php echo $this->PostBodyStart ?>

<?php echo $this->PrePageHeader ?>
<?php echo $this->PageHeader ?>
<?php echo $this->PostPageHeader ?>

<?php echo $this->PrePageMain ?>
<main id="page-main-region" class="page-main-wrapper" role="main">
    <div id="page-content-region" class="page-content-wrapper">
        <?php echo $this->PrePageContent; ?>
        <?php
        /**
         * Main page content
         */
        echo $this->content;
        ?>
        <?php echo $this->PostPageContent; ?>
    </div>
</main>
<?php echo $this->PostPageMain ?>

<?php echo $this->PrePageFooter ?>
<?php echo $this->PageFooter ?>
<?php echo $this->PostPageFooter ?>

<?php echo $this->PreBodyEnd ?>
</body>
</html>