<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2017 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
$entity = $this->context->getActionResult()->getEntity();
if (!$entity->hasImage()) {
    return;
}
?>
<div class="form-group">
    <div class="col-md-8 col-md-offset-4">
        <?php
        echo $this->plugin('image')
            ->thumbnail(
                $this->resizeImage($entity->getImageFullPath())->thumb(75, 75)
            )
        ?>
    </div>
</div>
