<?php

namespace WellCart\Catalog\Test\Unit\Repository;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-27 at 07:37:13.
 */
class FeaturesTest extends \WellCart\Test\TestCase
{

    /**
     * @var Features
     */
    protected $object;

    /**
     * @todo   Implement testToOptionsList().
     */
    public function testToOptionsList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testFinder().
     */
    public function testFinder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testCreateQueryBuilder().
     */
    public function testCreateQueryBuilder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testToGroupedOptionsList().
     */
    public function testToGroupedOptionsList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new Features;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
