<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2016 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
$this->headTitle(__('Forgot Password'));
?>
<div style="float:left; padding-right:16px;"><?php
    echo $this->gravatar(
        $this->zfcUserIdentity()->getEmail()
    )
    ?></div>
<h3><?php echo $this->translate('Hello'); ?>
    , <?php echo $this->zfcUserDisplayName() ?>!</h3>
<a href="<?php
echo $this->url(
    'zfcuser/logout'
)
?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
<div style="clear:both;"></div>
