<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2017 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */

$this->headTitle(__('Sign In'));

$form = $this->loginForm;

$form->prepare();
$this->strokerFormPrepare($form->getName(), $form);

$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');

$identity = $form->get('identity')
    ->setAttributes(
        [
            'placeholder' => __('Email'),
            'class'       => 'form-control'
        ]
    );
$credential = $form->get('credential')
    ->setAttributes(
        [
            'placeholder' => __('Password'),
            'class'       => 'form-control'
        ]
    );

$errors = $this->formElementErrors($identity);
?>
<div class="container">
    <div class="row">
        <?php if (!empty($errors)): ?>
            <div class="alert alert-danger"><?php echo $errors ?></div>
        <?php endif ?>
        <div class="col-md-offset-5 col-md-3">
            <?php echo $this->form()->openTag($form) ?>
            <div class="form-login">
                <h3><?php
                    echo $this->translate(
                        'Welcome, please sign in'
                    );
                    ?></h3>

                <p><?php echo $this->formInput($identity) ?></p>

                <p><?php echo $this->formInput($credential) ?></p>

                <div class="wrapper">
                    <div class="group-btn">
                        <button type="submit"
                                class="btn btn-primary btn-md"><?php
                            echo __(
                                'Sign In'
                            )
                            ?>
                            <i class="fa fa-sign-in"></i>
                        </button>

                        <?php if ($this->enableRegistration) : ?>
                            <?php echo str_repeat('&nbsp', 5) ?><a
                            href="<?php
                            echo $this->url(
                                'zfcuser/register'
                            )
                            ?>"><?php echo $this->translate('Sign up'); ?></a>
                        <?php endif; ?>

                        <?php echo str_repeat('&nbsp', 5) ?>
                        <a href="<?php
                        echo $this->url(
                            'user-account-recovery/initiate'
                        )
                        ?>"
                           class=""><?php echo __('Forgot?') ?>
                        </a>

                    </div>
                </div>
            </div>
            <?php echo $this->form()->closeTag() ?>
        </div>
    </div>
</div>