<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2017 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
?>
<div class="panel-heading panel-toolbar"
     data-spy="affix"
     data-offset-top="180">
    <h6 class="panel-title"><?php echo $this->formTitle ?></h6>

    <div class="heading-elements">
        <?php
        foreach ($this->form->getToolbarButtons() as $item):
            echo $this->formElement($item);
        endforeach;
        ?>

        <?php if ($this->form->backButton()): ?>
            <a href="<?php echo url_to_route() ?>"
               class="btn btn-default btn-circle"><i
                        class="fa fa-angle-left"></i> <?php
                echo __(
                    'Back'
                )
                ?> </a>
        <?php endif ?>

        <?php if ($this->form->resetButton()): ?>
            <button class="btn btn-default btn-circle"
                    type="reset">
                <i class="fa fa-reply"></i> <?php
                echo __(
                    'Reset'
                )
                ?></button>
        <?php endif ?>
    </div>
</div>