<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2016 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
?>
<div class="row grid-footer">
    <div class="col-md-12" id="<?php echo $this->gridId; ?>_footer">
        <p>
            <?php
            foreach ($this->massActions as $action) {
                /* @var $action \ZfcDatagrid\Action\Mass */
                ?>
                <a href="#" class="btn btn-default group-action"
                   data-url="<?php echo $action->getLink(); ?>">
                    <?php echo $this->translate($action->getTitle()); ?>
                </a>
                <?php
            }
            ?>
        </p>
    </div>
</div>
<script type="text/javascript">
    <?php $this->inlineScript()->captureStart(); ?>
    function <?php echo $this->gridId; ?>ChangeSelection(type) {
        $('#selection-type-<?php echo $this->gridId; ?>').val(type);
        var master = $('#checkbox-select-all-<?php echo $this->gridId; ?>');
        var checkboxes = $('input[type=checkbox]', '#table-<?php echo $this->gridId ?>').not(master);
        switch (type) {
            case 'all':
                master.prop('indeterminate', false)
                        .prop('checked', true)
                checkboxes.prop('checked', true);
                break;
            case 'selected':
                master.prop('checked', true)
                        .prop('indeterminate', true);
                checkboxes.prop('checked', true);
                break;
            case 'none':
                master.prop('checked', false)
                        .prop('indeterminate', false);
                checkboxes.prop('checked', false);
                break;
        }

    }
    $(document).ready(function () {
        $('#<?php echo $this->gridId; ?>_footer a.group-action').click(function () {
            var form = document.createElement('form');
            form.setAttribute('name', 'group_action');
            form.setAttribute('method', 'post');
            form.setAttribute('action', $(this).attr('data-url'));


            var checkboxes = document.getElementsByName('massActionSelected[]');
            for (i = 0; i < checkboxes.length; i++) {
                var node = checkboxes[i].cloneNode();
                node.name = 'ids[' + i + ']';
                form.appendChild(node);
            }

            var input = document.createElement("input");
            input.type = "hidden";
            input.name = "selection_type";
            input.value = $('#selection-type-<?php echo $this->gridId; ?>').val();
            form.appendChild(input);

            document.body.appendChild(form);
            form.submit();
            document.body.removeChild(form);
            return false;
        });
    });
    <?php $this->inlineScript()->captureEnd(); ?>
</script>