<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2017 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
$messenger->setMessageOpenFormat(
    '<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul><li>'
)
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $messenger->render(
    'error', array('alert', 'alert-dismissable', 'alert-danger')
);
echo $messenger->render(
    'info', array('alert', 'alert-dismissable', 'alert-info')
);
echo $messenger->render(
    'default', array('alert', 'alert-dismissable', 'alert-info')
);
echo $messenger->render(
    'warning', array('alert', 'alert-dismissable', 'alert-warning')
);
echo $messenger->render(
    'success', array('alert', 'alert-dismissable', 'alert-success')
);

$messenger->clearMessagesFromContainer();
