<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2016 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */

use WellCart\Utility\Config;

?>
<p class="copyright"><?php echo __('Copyright') ?> &copy; <?php
    echo date(
        'Y'
    )
    ?> <?php echo Config::get('wellcart.website.name') ?> <?php echo __(
        'All rights reserved.'
    ) ?></p>