<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2017 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
$messenger = $this->flashMessenger();
?>
<div class="container-fluid">
    <section class="notification-wrapper flash-notifications row">
        <?php
        include __DIR__ . '/_notifications.phtml';
        ?>
    </section>
</div>