<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2016 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
?>
<noscript>
    <div class="wellcart-base-html-notice noscript">
        <div class="notice-inner">
            <p>
                <strong><?php
                    echo __(
                        'JavaScript seems to be disabled in your browser.'
                    );
                    ?></strong><br/>
                <?php
                echo
                __(
                    'You must have JavaScript enabled in your browser to utilize the functionality of this website.'
                );
                ?>
            </p>
        </div>
    </div>
</noscript>