<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2017 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
$this->headTitle(__('Create New Password'));
$form = $this->form;
$form->prepare();
$form->setAttribute('class', 'form-signin');
$submit = $form->get('submit')
    ->setAttributes(
        [
            'class'             => 'btn btn-primary btn-block btn-signin',
            'role'              => 'button',
            'value'             => __('Change'),
            'data-disable-with' => __('Change'),
            'id'                => 'recover_account_submit_form',
        ]
    );;
?>
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-5">
            <?php echo $this->form()->openTag($form) ?>
            <fieldset>
                <legend><?php
                    echo __(
                        'New Password For Your Account'
                    )
                    ?></legend>
                <?php echo $this->formRow($form->get('newCredential')) ?>
                <?php echo $this->formRow($form->get('newCredentialVerify')) ?>
                <?php echo $this->formInput($submit) ?>

                <p><a href="<?php echo $this->url('zfcuser') ?>"
                      class=""><?php echo __('Back to Log in') ?></a></p>
            </fieldset>
            <?php echo $this->form()->closeTag() ?>

        </div>
    </div>
</div>