<?php
/**
 * WellCart Platform
 *
 * @copyright  Copyright (c) 2016 WellCart Development Team    http://wellcart.org/
 * @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
 */
$this->headTitle(__('Create New Password'));
$form = $this->form;
$form->prepare();
$form->setAttribute('class', 'form-signin');
$submit = $form->get('submit')
    ->setAttributes(
        [
            'class'             => 'btn btn-primary btn-block btn-signin',
            'role'              => 'button',
            'value'             => __('Change'),
            'data-disable-with' => __('Change'),
            'id'                => 'recover_account_submit_form',
        ]
    );
echo $this->headLink();
?>
<div class="container">
    <div class="card card-container">
        <?php echo $this->form()->openTag($form) ?>
        <fieldset>
            <legend><?php echo __('New Password For Your Account') ?></legend>
            <?php echo $this->formRow($form->get('newCredential')) ?>
            <?php echo $this->formRow($form->get('newCredentialVerify')) ?>
            <?php echo $this->formInput($submit) ?>

            <p><a href="<?php echo $this->url('zfcadmin') ?>">
                    <i class="fa fa-arrow-left"></i>
                    <?php echo __('Back to Log in') ?></a></p>
        </fieldset>
        <?php echo $this->form()->closeTag() ?>

    </div>
    <div class="card-container">
        <?php echo $this->partial('wellcart-base/item-view/copyright') ?>
    </div>
</div>