#
# WellCart Platform
#
# @copyright  Copyright (c) 2016 WellCart Dev Team (http://wellcart.org)
# @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
#
language: php

php:
  - 7.0


env:
  - DB=mysql DB_DRIVER=pdo_mysql DB_PORT=3306 DB_USERNAME=root
  - DB=pgsql DB_DRIVER=pdo_pgsql DB_PORT=5432 DB_USERNAME=postgres

dist: trusty
sudo: required

services:
  - mongodb
  - rabbitmq
  - memcached
addons:
  postgresql: "9.1"
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6  

before_install:
  - composer self-update && composer --version

before_script:
  - composer install
  - composer show

script: bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover report/clover.xml
  - bin/coveralls

matrix:
  fast_finish: true

notifications:
  email: false